Repository yunionio/ocadm, pull requests merged in 2019-12, with the labels that each got.

#7 host support
  go.mod
  go.sum
  pkg/cmd/cmd.go
  pkg/cmd/host.go
  pkg/cmd/init.go
  pkg/cmd/join.go
  pkg/options/constant.go
  pkg/phases/host/host.go
  pkg/phases/init/addons.go
  pkg/phases/init/data.go
  pkg/phases/join/data.go
  pkg/util/kubectl/client.go
  pkg/util/onecloud/onecloud.go
Labels: size/L

#8 bugfix: fix cmd host enable
  pkg/cmd/host.go
Labels: size/XS

#9 use default k8s node port range
  go.mod
  go.sum
  pkg/apis/constants/constants.go
  pkg/apis/v1/defaults.go
  pkg/phases/cluster/cluster.go
  pkg/phases/component/component.go
  pkg/util/onecloud/waiter.go
Labels: size/M

#10 fix init host.conf
  pkg/util/onecloud/onecloud.go
Labels: size/XS

#11 feature: support baremteal select node, add disable phase
  go.mod
  go.sum
  pkg/cmd/baremetal.go
  pkg/cmd/cmd.go
  pkg/cmd/host.go
  pkg/phases/baremetal/baremetal.go
  pkg/phases/host/host.go
Labels: size/L

#12 feature: enable host agent on join
  pkg/cmd/join.go
  pkg/phases/join/data.go
  pkg/util/onecloud/onecloud.go
Labels: size/M

#13 add label yunion controller
  README.md
  go.mod
  go.sum
  pkg/cmd/baremetal.go
  pkg/cmd/cmd.go
  pkg/cmd/host.go
  pkg/cmd/init.go
  pkg/cmd/join.go
  pkg/cmd/labels.go
  pkg/cmd/node.go
  pkg/options/constant.go
  pkg/phases/host/host.go
  pkg/phases/nodelabels/nodelabels.go
Labels: size/XL

#14 disable auto set k8s controller as onecloud controller
  pkg/cmd/join.go
Labels: size/XS

#15 add loki addons
  pkg/apis/constants/constants.go
  pkg/cmd/init.go
  pkg/options/constant.go
  pkg/phases/addons/calico/calico.go
  pkg/phases/addons/csi/csi.go
  pkg/phases/addons/csi/template.go
  pkg/phases/addons/grafana/grafana.go
  pkg/phases/addons/grafana/template.go
  pkg/phases/addons/helper.go
  pkg/phases/addons/loki/loki.go
  pkg/phases/addons/loki/template.go
  pkg/phases/addons/onecloudoperator/operator.go
  pkg/phases/addons/onecloudoperator/template.go
  pkg/phases/addons/traefik/template.go
  pkg/phases/addons/traefik/traefik.go
  pkg/phases/init/addons.go
  pkg/phases/init/data.go
Labels: size/XXL

#17 wait update cluster
  go.mod
  go.sum
  pkg/cmd/cluster.go
  pkg/phases/cluster/cluster.go
  pkg/util/kube/client.go
  pkg/util/kube/config.go
  pkg/util/kube/rollout.go
  pkg/util/onecloud/operator.go
Labels: size/XL
