Repository yunionio/ocadm, pull requests merged in 2020-02, with the labels that each got.

#20 cluster update adjust operator and component order
  pkg/phases/cluster/cluster.go
Labels: size/M

#21 Automated cherry pick of #20: cluster update adjust operator and component order
  pkg/phases/cluster/cluster.go
Labels: size/M

#22 Automated cherry pick of #20: cluster update adjust operator and component order
  pkg/phases/cluster/cluster.go
Labels: size/M

#23 Set default host config option ovn_south_database
  go.mod
  go.sum
  pkg/util/onecloud/onecloud.go
Labels: do-not-merge/hold, size/L

#24 Automated cherry pick of #23: go.mod: update yunion.io/x/onecloud{,-operator]
  go.mod
  go.sum
  pkg/util/onecloud/onecloud.go
Labels: size/L
