Repository yunionio/ocadm, pull requests merged in 2020-06, with the labels that each got.

#76 add operator priority schedule class
  pkg/phases/addons/onecloudoperator/template.go
Labels: lgtm, size/XS

#78 Automated cherry pick of #76: add operator priority schedule class
  pkg/phases/addons/onecloudoperator/template.go
Labels: size/XS

#77 Automated cherry pick of #76: add operator priority schedule class
  pkg/phases/addons/onecloudoperator/template.go
Labels: size/XS

#79 Automated cherry pick of #56: support upgrade
  go.mod
  go.sum
  pkg/cmd/init.go
  pkg/cmd/join.go
  pkg/options/generic.go
  pkg/phases/cluster/cluster.go
  vendor/github.com/joho/godotenv/.gitignore
  vendor/github.com/joho/godotenv/.travis.yml
  vendor/github.com/joho/godotenv/LICENCE
  vendor/github.com/joho/godotenv/README.md
  vendor/github.com/joho/godotenv/godotenv.go
  vendor/modules.txt
Labels: size/XL

#83 fix upgrade from v2
  pkg/cmd/init.go
  pkg/cmd/join.go
  pkg/options/generic.go
Labels: size/S

#84 Automated cherry pick of #83: fix upgrade from v2
  pkg/cmd/init.go
  pkg/cmd/join.go
  pkg/options/generic.go
Labels: size/S

#85 Automated cherry pick of #83: fix upgrade from v2
  pkg/cmd/init.go
  pkg/cmd/join.go
  pkg/options/generic.go
Labels: size/S

#80 addon: add metrics server and remove itsm server
  pkg/apis/constants/constants.go
  pkg/phases/addons/metricsserver/metricsserver.go
  pkg/phases/addons/metricsserver/template.go
  pkg/phases/component/init.go
  pkg/phases/init/addons.go
Labels: size/L

#81 Automated cherry pick of #80: addon: add metrics server and remove itsm server
  pkg/apis/constants/constants.go
  pkg/phases/addons/metricsserver/metricsserver.go
  pkg/phases/addons/metricsserver/template.go
  pkg/phases/component/init.go
  pkg/phases/init/addons.go
Labels: size/L

#88 fetch itsm config from globalrc
  pkg/phases/cluster/cluster.go
Labels: size/S

#89 Automated cherry pick of #88: fetch itsm config from globalrc
  pkg/phases/cluster/cluster.go
Labels: size/S

#90 feature: addon longhorn
  pkg/apis/constants/constants.go
  pkg/cmd/base.go
  pkg/cmd/cmd.go
  pkg/cmd/init.go
  pkg/cmd/longhorn.go
  pkg/options/constant.go
  pkg/phases/addons/longhorn/longhorn.go
  pkg/phases/addons/longhorn/template.go
  pkg/phases/baremetal/baremetal.go
  pkg/phases/init/addons.go
  pkg/phases/longhorn/longhorn.go
  pkg/phases/longhorn/migrate.go
  pkg/util/kubectl/client.go
Labels: size/XXL

#94 Automated cherry pick of #93: update DefaultCalicoVersion to 3.12.1
  pkg/apis/constants/constants.go
Labels: size/XS

#95 update vendor for 3.3
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/loadbalancer.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/secgroup.go
Labels: size/S
