Repository yunionio/ocadm, pull requests merged in 2020-07, with the labels that each got.

#96 fix create region zone where upgrade from v2
  pkg/cmd/init.go
  pkg/phases/cluster/cluster.go
Labels: size/S

#97 Automated cherry pick of #96: fix create region zone where upgrade from v2
  pkg/cmd/init.go
  pkg/phases/cluster/cluster.go
Labels: size/S

#98 Automated cherry pick of #96: fix create region zone where upgrade from v2
  pkg/cmd/init.go
  pkg/phases/cluster/cluster.go
Labels: size/S

#102 Hotfix/rex update vendor for 3.3
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/onecloud-operator/pkg/apis/onecloud/v1alpha1/defaults.go
  vendor/yunion.io/x/onecloud-operator/pkg/apis/onecloud/v1alpha1/types.go
  vendor/yunion.io/x/onecloud-operator/pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  vendor/yunion.io/x/onecloud-operator/pkg/controller/base_control.go
  vendor/yunion.io/x/onecloud-operator/pkg/controller/cronjob_control.go
  vendor/yunion.io/x/onecloud-operator/pkg/controller/deployment_control.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/cloudmon_ping.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/cloudmon_report_host.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/cloudmon_report_server.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/cloudmon_report_usage.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/component.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/etcd.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/externalproject.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guestnetwork.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/host.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/input.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/schedtag.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/secgroup.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/cas.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/config.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/consts.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/identityprovider.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/input.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/input.go
  vendor/yunion.io/x/onecloud/pkg/apis/list.go
  vendor/yunion.io/x/onecloud/pkg/apis/output.go
  vendor/yunion.io/x/onecloud/pkg/apis/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/appsrv/appsrv.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/consts.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/waitstatus.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/input.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/session.go
  vendor/yunion.io/x/onecloud/pkg/monitor/options/options.go
  vendor/yunion.io/x/onecloud/pkg/util/procutils/procutils.go
  vendor/yunion.io/x/onecloud/pkg/util/seclib2/certfile.go
  vendor/yunion.io/x/pkg/util/timeutils/timeutils.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/XXL

#104 update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/string.go
  vendor/yunion.io/x/jsonutils/write.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/cloudid.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/cloudmon.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/host-image.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/telegraf.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dbinstance_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/scheduled_task.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/scheduled_task_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/secgroup.go
  vendor/yunion.io/x/onecloud/pkg/apis/const.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/oidc.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/saml.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/alert.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/alertnotification.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/commalert.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/doc.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/meteralert.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/nodealert.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/notification.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/suggestsys_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/suggestsysalert.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/suggestsysrule.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/suggestsysruleconfig.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/template.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/types.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/unifiedmonitor_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/clouduser.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/scoperesources.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_amount_estimations.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_cloudgroup.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_cloudgroupcaches.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_cloudgrouppolicies.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_cloudgroupusers.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_cloudpolicy.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_clouduserpolicies.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_cloudusers.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_commonalert.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_daily_bills.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_itsm_extra_jira.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_scheduledtask.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_unifiedmonitor.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/scoperesources.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/oidc.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/saml.go
  vendor/yunion.io/x/onecloud/pkg/util/httputils/httputils.go
  vendor/yunion.io/x/onecloud/pkg/util/stringutils2/sortedstrings.go
Labels: size/XXL

#105 longhorn deploy misc fix
  pkg/phases/addons/longhorn/longhorn.go
  pkg/phases/addons/longhorn/template.go
  pkg/phases/cluster/cluster.go
  pkg/phases/longhorn/longhorn.go
  pkg/phases/longhorn/migrate.go
Labels: size/M

#106 Automated cherry pick of #105: longhorn deploy misc fix
  pkg/phases/addons/longhorn/longhorn.go
  pkg/phases/addons/longhorn/template.go
  pkg/phases/cluster/cluster.go
  pkg/phases/longhorn/longhorn.go
  pkg/phases/longhorn/migrate.go
Labels: size/M

#107 修复 keepalived master state bug
  pkg/apis/constants/constants.go
  pkg/phases/addons/keepalived/keepalived.go
Labels: size/M

#108 Automated cherry pick of #107: 修复 keepalived master state bug
  pkg/apis/constants/constants.go
  pkg/phases/addons/keepalived/keepalived.go
Labels: size/M

#111 高可用部署主备选取应将kube-apiserver是否工作考虑进去
  pkg/apis/constants/constants.go
  pkg/cmd/init.go
  pkg/cmd/join.go
  pkg/phases/addons/keepalived/keepalived.go
  pkg/phases/init/data.go
  pkg/phases/join/data.go
Labels: size/M

#112 Automated cherry pick of #111: 高可用部署主备选取应将kube-apiserver是否工作考虑进去
  pkg/apis/constants/constants.go
  pkg/cmd/init.go
  pkg/cmd/join.go
  pkg/phases/addons/keepalived/keepalived.go
  pkg/phases/init/data.go
  pkg/phases/join/data.go
Labels: size/S

#114 Automated cherry pick of #113: ocadm create cluster, 延时等待容错
  pkg/phases/cluster/cluster.go
Labels: size/XS

#113 ocadm create cluster, 延时等待容错
  pkg/phases/cluster/cluster.go
Labels: size/XS
