Repository yunionio/ocadm, pull requests merged in 2020-05, with the labels that each got.

#57 修改itsm的template
  pkg/phases/component/itsm.go
Labels: size/XS

#58 Automated cherry pick of #57: 修改itsm的template
  pkg/phases/component/itsm.go
Labels: size/XS

#59 Automated cherry pick of #57: 修改itsm的template
  pkg/phases/component/itsm.go
Labels: size/XS

#60 Automated cherry pick of #57: 修改itsm的template
  pkg/phases/component/itsm.go
Labels: size/XS

#56 ocadm support upgrade
  go.mod
  go.sum
  pkg/cmd/init.go
  pkg/cmd/join.go
  pkg/options/generic.go
  pkg/phases/cluster/cluster.go
  vendor/github.com/joho/godotenv/.gitignore
  vendor/github.com/joho/godotenv/.travis.yml
  vendor/github.com/joho/godotenv/LICENCE
  vendor/github.com/joho/godotenv/README.md
  vendor/github.com/joho/godotenv/godotenv.go
  vendor/modules.txt
Labels: size/XL

#62 disable loki stack
  pkg/phases/init/addons.go
Labels: size/XS

#66 Automated cherry pick of #65: 多网卡环境下 calico 网卡选择策略
  pkg/cmd/init.go
  pkg/options/constant.go
  pkg/phases/addons/calico/calico.go
  pkg/phases/addons/calico/template.go
  pkg/phases/init/addons.go
  pkg/phases/init/data.go
Labels: size/L

#69 Automated cherry pick of #68: set default control plane endpoint
  pkg/apis/v1/defaults.go
  pkg/cmd/init.go
Labels: size/S

#68 set default control plane endpoint
  pkg/apis/v1/defaults.go
  pkg/cmd/init.go
Labels: size/S

#70 bugfix: set node override name
  pkg/apis/v1/defaults.go
  pkg/util/onecloud/onecloud.go
Labels: size/S

#71 Automated cherry pick of #70: set node override name
  pkg/apis/v1/defaults.go
  pkg/util/onecloud/onecloud.go
Labels: size/S

#72 修改itsm镜像仓库信息，和项目信息对应
  pkg/phases/component/itsm.go
Labels: lgtm, size/XS

#74 Automated cherry pick of #72: 修改itsm镜像仓库信息，和项目信息对应
  pkg/phases/component/itsm.go
Labels: size/XS

#75 Automated cherry pick of #72: 修改itsm镜像仓库信息，和项目信息对应
  pkg/phases/component/itsm.go
Labels: size/XS
