Repository yunionio/ocadm, pull requests merged in 2020-03, with the labels that each got.

#25 fix docker client version not match
  go.mod
  go.sum
Labels: size/XS

#26 Automated cherry pick of #25: fix docker client version not match
  go.mod
  go.sum
Labels: size/XS

#34 fix getRepoImageName parse sha256 tag
  go.mod
  go.sum
  pkg/phases/cluster/cluster.go
  pkg/phases/cluster/cluster_test.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud-operator/pkg/apis/onecloud/v1alpha1/defaults.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/component.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/host.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/sync.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/utils.go
  vendor/yunion.io/x/onecloud-operator/pkg/util/image/reference.go
  vendor/yunion.io/x/onecloud/pkg/apis/cloudprovider/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/hostman/options/options.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/managers.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_contacts.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_groups.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
Labels: size/XXL

#35 Automated cherry pick of #34: fix getRepoImageName parse sha256 tag
  go.mod
  go.sum
  pkg/phases/cluster/cluster.go
  pkg/phases/cluster/cluster_test.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud-operator/pkg/apis/onecloud/v1alpha1/defaults.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/component.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/host.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/sync.go
  vendor/yunion.io/x/onecloud-operator/pkg/manager/component/utils.go
  vendor/yunion.io/x/onecloud-operator/pkg/util/image/reference.go
  vendor/yunion.io/x/onecloud/pkg/apis/cloudprovider/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/hostman/options/options.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/managers.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_contacts.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_groups.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
Labels: size/XXL

#37 wait add more checks
  pkg/phases/cluster/cluster.go
  pkg/util/onecloud/operator.go
Labels: size/S

#39 adjust k8s extra args
  pkg/apis/v1/defaults.go
  pkg/cmd/init.go
  pkg/phases/component/init.go
Labels: size/S

#40 Automated cherry pick of #39: adjust k8s extra args
  pkg/apis/v1/defaults.go
  pkg/cmd/init.go
  pkg/phases/component/init.go
Labels: size/S

#41 编译时接受外部 tag
  hack/make-package.sh
Labels: size/XS

#42 Automated cherry pick of #41: 编译时接受外部 tag
  hack/make-package.sh
Labels: size/XS

#43 Automated cherry pick of #41: 编译时接受外部 tag
  hack/make-package.sh
Labels: size/XS
